### ISSUE TITLE
[Techniques] Spikes, spike&stabilize, feature flags

### ISSUE THREAD

**Issue by nyctef** [red-gate/Tech-Radar#104]
Just creating one issue for these for now since they're all kind of interrelated:

- **Technical spikes**: timeboxed prototype/proof-of-concept for some feature or technical implementation detail. Usually done with minimal quality (since they're never intended to be real code), implemented on a branch and then thrown away
- **Feature flags/toggles**: some way to prevent code in `master` from affecting the way the product behaves. There are lots of different types of toggles: they might be set at compile or run time; they might be purely internal or visible to the user, and so on. Much more details here: https://martinfowler.com/articles/feature-toggles.html
- **Spike & stabilize**: a technique for delaying investment in code until it has proven to be valuable: every bit of new code is initially written as "spikes" (unlike technical spikes these usually have a basic level of quality) and then after some trigger (eg the code is touched again / the feature becomes popular / X weeks have passed / etc) the code is brought up to a "high" level of quality with full test coverage, better error handling, documentation, etc

We might combine these techniques: eg use a feature flag to allow spikes to be committed to `master` early, and then turn off the feature flag once the spike has reached a basic level of quality

There's a lot more we could (and have) written about these topics, though :)

**Comment by tugberkugurlu** [comment]
> We've been doing feature flags for a while now on Figleaf and they've been working well for us - personally I think they should be in Adopt and everyone should be using them.

We have been using them for a while as well and my personal view on that is that it works really well and also support short-lived PRs and master being always releasable. @red-gate/spiders any specific views on this?

**Comment by ChrisLambrou** [comment]
> @red-gate/spiders any specific views on this?

Agreed. It's great for keeping feature requests small, getting code into master even before it's ready to expose to customers, and avoiding horrible merge conflicts across long-lived feature branches. At the time when The Spiders were considering adopting them, I did a bit of research across a bunch of teams to work out how they're being used. I could dig out the results, which was really just a description of a feature flag's purpose and life cycle. Might be worth writing that up in our Product Dev area of the info site?

**Comment by tugberkugurlu** [comment]
> Not entirely related to tech radar but I want to put this here so that there is an awareness if anyone else wants to do the same. It would be great to get this in a blog post but only if I had time for everything 😄 

We also have a mechanism which integrated feature flags into ASP.NET Core. It takes advantage of ASP.NET MVC Core's action location, [config ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.1) and [options ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.1) mechanisms to hook this into the system in a type safe way. It allows us to:

 - Hook the feature flagging into the system with a strongly typed model, which is discovered through the defined convention mechanism: https://github.com/red-gate/SQLEstateManager-vNext/blob/68029f5072392cbe633686f470d70140bcfbd06e/src/RedGate.SqlEstateManager.WebAPI.Core/Features/AuthTokenFeatureFlag.cs 
 - Feature flag APIs so that they are hidden from the swagger docs and action location: https://github.com/red-gate/SQLEstateManager-vNext/blob/68029f5072392cbe633686f470d70140bcfbd06e/src/RedGate.SqlEstateManager.WebAPI.Core/Controllers/Internal/AuthTokensController.cs#L43
 - Enable/disable them through any supported config mechanism such as file config. environment variables, etc.: https://github.com/red-gate/SQLEstateManager-vNext/blob/68029f5072392cbe633686f470d70140bcfbd06e/src/SqlEstateManagerWebAPI/appsettings.Debug.json#L12-L14
 - Making feature flags injectable through ASP.NET Core's Options mechanism (e.g. `IOptions<AuthTokenFeatureFlag>`) so that you can reference these anywhere in the codebase and it would honor the config settings.
 - Also push these to the frontend through the APIs: https://github.com/red-gate/SQLEstateManager-vNext/blob/68029f5072392cbe633686f470d70140bcfbd06e/src/WebClient/src/components/Shared/NavigationHorizontal.tsx#L36 so that we can also use these for front end changes.
