### ISSUE TITLE
[Techniques] "Stop the line" when a build is red

### ISSUE THREAD

**Issue by Greg-Smulko** [red-gate/Tech-Radar#108]
How about agreeing that a red build is the team's top-priority, no exceptions?

It may mean investing some time upfront to fixing flaky tests. 
On the other hand, it allows spotting regressions quickly (as we did recently with a newly introduced flaky test, which occurred to be a race condition in a production code).

A bit of background: https://kanbanize.com/blog/stop-the-line/

**Comment by ChrisHurley** [comment]
I agree that it's top priority to fix it... I think what's interesting is whether we meant that stop the line = someone should look at fixing it immediately, or stop the line = everyone stops all work on other branches too? I'm not sure if the latter is necessarily required.

**Comment by fffej** [comment]
I don't think this is controversial? If the build is red, then someone on the team is fixing it and nothing else will touch the master branch until it's green again.

@Greg-Smulko Could you create a PR for this?

**Comment by nyctef** [comment]
> I don't think this is controversial? If the build is red, then someone on the team is fixing it and nothing else will touch the master branch until it's green again.

> or stop the line = everyone stops all work on other branches too? I'm not sure if the latter is necessarily required.

I'm not sure if it's strictly necessary for us for a red build to block the whole team, but that does appear to be how "stop the line" is described in the article, so I wouldn't want to say we were adopting it unless we were properly stopping the line.

I suspect there's a complacency that creeps in when you allow the burden of fixing the build be placed on one person and allow the rest of the team to learn to ignore red builds 😛.

As we move towards trunk-based development, then red master builds will block the team more and more (since people would actually be blocked if they can't work on master) so I think this might be a good practice to try and explore properly.

**Comment by Greg-Smulko** [comment]
> I think what's interesting is whether we meant that stop the line = someone should look at fixing it immediately, or stop the line = everyone stops all work on other branches too? I'm not sure if the latter is necessarily required.

> I suspect there's a complacency that creeps in when you allow the burden of fixing the build be placed on one person and allow the rest of the team to learn to ignore red builds 😛.

Perhaps a middle ground would be to stop everyone's work to acknowledge that the build is broken, discuss it and decide who's fixing it as a top priority. Then the rest of the team can continue their work.

Thoughts?

**Comment by ChrisHurley** [comment]
@Greg-Smulko I think we're planning on trying that in the new year :)
