### ISSUE TITLE
[Techniques] Check in R# Settings

### ISSUE THREAD

**Issue by fffej** [red-gate/Tech-Radar#109]
Some teams have a checked in version of the R# settings for code inspections. This means everyone is consistent and (hopefully!) ends some of the debates that waste time.

My feeling is this should be in Adopt.

At the risk of starting a 🔥 war - do you think it's worth getting a common set of R# guidelines for Product Division?

**Comment by angellaa** [comment]
I agree this should be Adopt.

We should have a setting file ready to use when you start a new project from scratch. Then each team can make a few changes if considered appropriate for their code base.

In the Versioning teams, we spent a significant effort to create this shared settings file and then apply everything with a single click on all our code bases over Christmas last year. It really helped us to avoid wasting time debating style. So that file could be a good starting point for a Product Division shared settings file.

**Comment by garethbragg** [comment]
Checked in R# settings gets a big 👍 from me.

Avoiding the 🔥 section for now :)

**Comment by nyctef** [comment]
+1 for "automate your style guide as much as possible"

Personally I don't think a division-wide style guide is worth it - the cost of getting everyone to agree is too high, and the main benefit (minimizing switching costs between codebases) is kind of moot if you can get a tool to handle all your style differences anyway :)

**Comment by fffej** [comment]
@angellaa Fancy creating a PR for this? I agree that it should be per project rather than for the organization.

**Comment by angellaa** [comment]
Sure, I'll do it
