### ISSUE TITLE
Mocking Frameworks

### ISSUE THREAD

**Issue by fffej** [red-gate/Tech-Radar#13]
We use quite a few mocking frameworks

- [NSubstitute](http://nsubstitute.github.io/)
- [Moq](https://github.com/Moq/moq4/wiki/Quickstart)
- [Rhino Mocks](https://hibernatingrhinos.com/oss/rhino-mocks)

Where should they be on the Tech Radar?

**Comment by nyctef** [comment]
personal opinion: the first question to answer is "Do I need a mocking library?" The answer here will depend on [what kind of TDD you're doing](https://github.com/testdouble/contributing-tests/wiki/Test-Driven-Development) and how you're arranging your [boundaries](https://www.youtube.com/watch?v=yTkzNHF6rMs).

I don't know how this question fits on the Tech Radar :)

If you've decided you want a mocking library, I think they're all roughly equivalent and fine to use - I've had a decent experience with Moq and a terrible experience with RhinoMocks (although to be fair in the latter case we were using [the old record/playback API](https://stackoverflow.com/q/901353/895407) with strict mocks, which turned out to be a terrible idea which I believe RhinoMocks has since moved away from). Just pick the one which you think has the best syntax?

**Comment by smobs** [comment]
NSubstitute was fine for me

**Comment by MichelleTaylorRG** [comment]
I have an irrational prejudice against Moq because it has a stupid name. Other than that I've never found a substantial difference between NSubstitute and Moq so we should pick whatever one we are using in most products to put in the middle and stick the other one out in Endure.

**Comment by ChrisHurley** [comment]
I like that NSubstitute doesn't require setup lambdas and `.Object` calls like Moq.

**Comment by ChrisLambrou** [comment]
FWIW, COREDev had an interesting reason for using RhinoMocks rather than NSubstitute or Moq. With the latter two libraries, you can often end up writing code that follows this pattern:

1. Set up your mock objects in some non-trivial way.
2. Exercise your SUT.
3. Verify the expectations in your mock objects in a way that precisely duplicates the code in step 1.

When the mock set up is elaborate, that duplication is horrible. It's avoided with RhinoMocks because the test pattern looks like this instead:

1. Set up your mock objects in some non-trivial way.
2. Exercise your SUT.
3. Verify all expectations with a single call to `.VerifyAllExpectations()` on your mocks objects.

When the bulk of the tests involve setting up the mocks, as often turns out to be the case, it results in much more compact, readable tests.

**Comment by ChrisLambrou** [comment]
I suppose another consideration is that if you find yourself creating lots of elaborate mocks, maybe it's time to use fakes instead. They're used quite a lot in the Redgate Usage Client. Here's one if its internal interfaces for accessing the registry:

https://github.com/red-gate/RedGate.Usage.Client/blob/master/RedGate.Usage.Client/Providers/Registry/IRegistryProvider.cs

And here's a corresponding fake used in the tests:

https://github.com/red-gate/RedGate.Usage.Client/blob/master/RedGate.Usage.Client.Tests/Providers/Registry/FakeRegistryProvider.cs

Given the amount of mocking of `IRegistryProvider` that we previously had in our tests, replacing them with a fake got rid of loads of code and made the associated tests much simpler.

**Comment by ChrisLambrou** [comment]
Not sure where "Fakes" fit in the mocking frameworks part of the tech radar, though. They're really more of a technique for avoiding taking a dependency on a mocking framework.

**Comment by fffej** [comment]
Rhino Mocks - last commit Oct 11 2010 (https://github.com/hibernating-rhinos/rhino-mocks). [Groups](https://groups.google.com/forum/#!topic/RhinoMocks/mShjU5sF1ig) suggests it'll never support .NET Core.

Retire:
* Rhino Mocks.

**Comment by samblackburn** [comment]
Multiple mocking frameworks can coexist so at least the change can be made incrementally.  That said, I don't think I'd bother moving a large test suite from Moq to NSubstitute or vice versa just for the sake of uniformity.

Mocks vs fakes are different tools for different jobs: A simple `Mock<IFur>()` will let me avoid nullrefs without the risk of side effects, while a fake makes more sense when the same complex behaviour is needed by many tests.

I think this puts fakes, Moq and NSubstitute into "Explore" but I could be persuaded otherwise.

**Comment by fffej** [comment]
Sounds sensible @samblackburn - wonder if we could be a bit more opinionated though? If we have too much in "Explore" then we'll not start to converge.

Adopt  - NSubstitute (easier to use than Moq as @ChrisHurley mentioned)
Endure - Moq (as @samblackburn says changing it over for the sake of uniformity seems like a bad idea so endure seems more sensibel than retire)
Explore - Fakes (as a technique)
Retire - Rhino Mocks (doesn't support .NET Standard / .NET Core and not actively maintained).
