### ISSUE TITLE
JavaScript - Endure?

### ISSUE THREAD

**Issue by allymparker** [red-gate/Tech-Radar#15]
So just cos I want to be that guy...

> Endure - This is no longer how we do things. It is OK for this to be used in Product Development, but don't add more of it and migrate off it wherever possible.

I don't see how JS can be put in this ring.  A lot of people like TS, but I think there's a time and a place for plain ES6+.  Eg at the start of a project, only adding the extra layer if/when needed .

I personally haven't seen a significant benefit over using TS and found the tooling and extra layer to be more of a hindrance. 

![image](https://user-images.githubusercontent.com/2056009/47865152-5ce36d00-ddf3-11e8-946d-d2a85c126404.png)

**Comment by smobs** [comment]
@allymparker new project -> json straight into an api?
If we are transpiling JSX anyway then adding typings is worth it.
TS tooling is well supported by ~our overlords~ MS.

**Comment by smobs** [comment]
You are right that TS is only for devs who make mistakes.

**Comment by ChrisHurley** [comment]
I find the reliable IntelliSense that TypeScript gives makes it more discoverable, as well as giving me more confidence that the code is correct.

**Comment by andrew-farries** [comment]
I like modern (ie ES6+) Javascript and don't understand a lot of the hostility directed towards it. 

Things we could consider for the _Explore_ section here:

* [Flow](https://flow.org/) - Facebook's attempt at adding some static type safety to JS - not a language like Typescript, it just lets you add some type information to plain JS.
* [ReasonML](https://reasonml.github.io/) - A statically typed compiles-to-JS functional programming language.

**Comment by smobs** [comment]
I agree Andrew, modern JavaScript is fine. Typescript adds some worthwhile benefits on top.

What do you see as the benefits of flow vs typescript?

Also I'm a bit dubious that we can convince RG to use ocaml(although it would be awesome).
________________________________

**Comment by allymparker** [comment]
So are we saying modern JS (ES6+) is fine as well as TS?

**Comment by smobs** [comment]
I believe the aim of the radar is consistency and deliberate choice so we should pick one and TS is a bit better

**Comment by allymparker** [comment]
So are you writing your webpack config in TS?

**Comment by allymparker** [comment]
We’re not discussing removing C# from the tech radar

**Comment by smobs** [comment]
We aren't talking about removing JS from the radar either.
Webpack configs are glorified JSON, and actually it's a bit magic and would benefit from types.

**Comment by smobs** [comment]
Sure though JS is fine for build configuration, doesn't mean its in adopt.

**Comment by ojhall** [comment]
`Adopt - This is the technology you should be choosing to solve a problem. Everything in here forms our default set of technology choices (for example, C#)`

I don't think the fact that our webpack config files are written in JS qualifies the language to be one of our 'default technologies we choose to solve problems', and if it does, so does so much other technology that the radar's Adopt segment will become uselessly huge.

**Comment by allymparker** [comment]
(For ref, there is _no_ sarcasm in any of the below)
> it's a better default choice for Redgate (we're mostly C# developers and static typing feels more familiar).

I guess I'm comfortable with weak types, chrome debug tools, Jasmine/test coverage and PropTypes for components. I get it's not for everyone and if it makes more sense for RG as a whole then it should win out on my personal taste! 

I just not sure adding TS at this point in time with Monitors code and with little experience of TS on the team is the right thing to do? (I think @adrianbanks used it a bit in SoC). 

I do realise it's easy to kick the "no right time" can down the road forever tho... 😛 

@ffej What expectations/support can be put in place for teams in this scenario?

> Don't add new usage of this to existing products, but you're fine to continue existing uses.

What would that mean for new Estate experiments/screens in Monitor and for early stage prototypes pre-product division or experiments as a whole?

**Comment by santiaago** [comment]
I am with @allymparker on this, JS is the main language and is here to stay.

I would allow both, JavaScript and TypeScript. JavaScript allows me to go fast and it never gets in my way. I don’t see a problem in both coexisting, also, TypeScript is a JavaScript superset so they will alway exist together.

For new projects and foundry especially I would alway go for JavaScript over TypeScript is speeds our work without a doubt.

Also, the context switching between JavaScript and TypeScript is minimal due to TypeScript being a super set of JavaScript, when you are not creating signatures you are essentially using JavaScript anyway.

**Comment by fffej** [comment]
Would you be more specific about JS? Do we say 

Adopt
* JavaScript (ES6+)
* TypeScript

Perhaps we clarify the different benefits in the description for each?

**Comment by smobs** [comment]
JS in endure means you can keep using it for your product if you are already using it. Plus as @Santiaago mentions the context switching is easy whilst your codebase converts.
I believe that it is quicker to write code in dynamic languages. If we are writing prototypes to throw away then maybe we should write the whole thing in JS including the backend. Can we have "prototyping languages" as a thing?

**Comment by fffej** [comment]
I don't think we're going to get to a _right_ answer here because it's not as simple as that. I buy @santiaago and @allymparker description of the benefits of modern JavaScript, and TypeScript clearly has a fair bit of ❤️  too. 

We'll review the Tech Radar regularly, so let's get a bit more experience before we start to be more opinionated. II've separated out ES6 because modern JavaScript is way more pleasant and I've assumed that's what everyone is using?  

The below reflects what I think the discussion above says. 👍 (or even better create a PR!) if you agree with this and we'll close this off for now.

Adopt
* JavaScript (ES6+) - We use JavaScript for rapid prototyping of ideas because it allows us to go faster. In code bases where we already have significant JavaScript we will continue to use modern JavaScript.
* TypeScript - We have a preference for TypeScript in production code because the optional type safety can help and improved tool support.

Retire
* JavaScript (pre ES6) - We don't use older versions of JavaScript. ES6 features like promises, modules and classes significantly improve the JavaScript experience, and tools like BabelJS allow us to adopt this with confidence.

**Comment by smobs** [comment]
:+1:

**Comment by fffej** [comment]
Thanks all - clearly a contentious topic, but we've done it 🎆 🍾
