### ISSUE TITLE
Feature Usage Reporting

### ISSUE THREAD

**Issue by MichelleTaylorRG** [red-gate/Tech-Radar#17]
Appinsights and our own in house Usage stuff that feeds that feels like it should be on here somewhere. We still have a few other things kicking around (not just SA FUR but also Google Analytics) which I think we're trying to kick?

**Comment by rmc47** [comment]
Raygun in "retire"?

**Comment by fffej** [comment]
I agree. I spoke with @nyctef, @samblackburn and @fredjeronimo about this earlier and I think the model we should be working towards is `RedGate.Usage.Client` being extended to handle faults/errors.

If we manage to do this, then we can use a vendor neutral thing on our side, and all the choosing where to go can be done by hanging handlers off the message bus. This is what we do for App Insights and means we can change from MixPanel to AppInsights without needing to rebuild the code.

The only problem is we haven't built this yet 😄

**Comment by adrianbanks** [comment]
@rmc47 It's interesting you say that, as the SQL Monitor team has just agreed to introduce it. Any particular reason as to why?

**Comment by rmc47** [comment]
@adrianbanks What @fffej said, basically, though I realise that doesn't help you immediately. (But it seems a mild shame to introduce it now if you aren't already using it, knowing that we have a better plan on the table.)

I _thought_ I'd heard of other teams moving away from Raygun towards AppInsights - but I may have been mistaken.

**Comment by fredjeronimo** [comment]
@rmc47 , @adrianbanks  - I just wanted to clarify that the idea behind our chat yesterday was not to retire Raygun per se. Raygun has a lot of advantages going for it and the functionality it provides out of the box is very helpful to both the development teams and support. I'd be very surprised in AppInsights would be able to do all of that. We've been very happy with it in Prompt and I've done an analysis on the pros/cons of it a while back (you can read about it [here](https://info.red-gate.com/display/SP/Raygun)).

The problem is that we currently have Raygun tightly coupled on the client side and ideally we would have it abstracted away from the products in a message bus layer.  As @fffej mentioned "If we manage to do this, then we can use a vendor neutral thing on our side, and all the choosing where to go can be done by hanging handlers off the message bus."

**Comment by ChrisHurley** [comment]
I wasn't aware that teams were trying to use AppInsights as a way of recording errors - would be interesting to see how that works if so.

Raygun is ok, but I don't particularly love it.

**Comment by garethbragg** [comment]
I'd suggest we tackle the Raygun question separately. That's Error Reporting, not Feature Usage Reporting. I think we're in different places on those two domains.

For usage reporting:

Adopt: RedGate.Usage.Client
Adopt: AppInsights
Retire: MixPanel
Retire: Google Analytics
Retire: Smart Assembly

For error reporting, I think the current state is already on the [tech radar](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fred-gate%2FTech-Radar%2Fmaster%2Fradar.csv):

Adopt: Raygun
Retire: Smart Assembly
