### ISSUE TITLE
Remove F# from Tech Radar

### ISSUE THREAD

**Issue by fffej** [red-gate/Tech-Radar#172]
## What change would you like to make to the tech radar?

Remove F# from Explore because there is no team committed to exploring it.

Our current development language stack is C# / TypeScript / JavaScript. These are languages with a common lineage (e.g. the `{}` family) and transferring skills from one to the other is fairly easy. F# is from a different lineage (The ML Family) and requires a different set of skills and capabilities.

Although I'm a huge fan of functional programming, I don't think now is the right time for us to invest in exploring F#. This year is about the theme of convergence and having an outlier technology would go against this theme and not set us up to scale for the future. 

This doesn't rule out learning F# in 10% time, but I do not think we should write any production code/tests using F# in 2019.

**Comment by smobs** [comment]
LGTM
I'd reiterate the focus on consistency, this issue boils down to us not wanting to introduce any new languages in 2019.

**Comment by krzysztofkroczak** [comment]
...
It's annoying. It's the same .NET platform!
I didn't push people to change Redgate code without giving some learning, which I start doing from June 2018. All new people said that they could follow the prepared katas and understand it (please ask @eFuller96, @Mikeywalsh, @panagis for confirmation if needed). So I don't think that it comes from ML language is a problem at all. 
At the same time, new people which I've hardly try to bring to the guild, sneakily they've got an invitation for code clean up workshop which means that they can't attend the guild (so they were there on guild meeting once or twice).
I think that it's unfair to say don't use it because it comes from ML. We didn't get any support from Redgate to try it. So it's just unfair.
I am happy to discuss it more.
