### ISSUE TITLE
[Library] Enforce some architectural decisions as unit tests

### ISSUE THREAD

**Issue by angellaa** [red-gate/Tech-Radar#236]
## What change would you like to make to the tech radar?
Thoughwork added ArchUnit in Trial in their own radar.

I have just found a simple and easy to use a library built for .NET that could be used in our projects
https://www.ben-morris.com/writing-archunit-style-tests-for-net-and-c-for-self-testing-architectures/

## Why do you believe this is valuable to Redgate?
We can enforce some architectural/design decisions and make sure we preserve them over time (or more deliberately change them as the architecture evolve). It's too easy to reference projects without thinking about the consequences of doing it. Having some tests to enforce a project structure we would like to preserve could be powerful.

## Where should this be on the tech radar?
We should explore if this library can work for us and it's reliable enough.

### If this should be in the _Explore_ ring, who is committed to exploring it?
I (Andrea) am happy to give it a go when I find some time but feel free to play with it if you want.

**Comment by fffej** [comment]
@angellaa I'm really looking for a team to commit to exploring it. Do you think there are any valuable places to use in across versioning?

I'd love to see tests that verify that anything in the core of SCA doesn't depend on Oracle/SQL packages.

**Comment by nyctef** [comment]
> I'd love to see tests that verify that anything in the core of SCA doesn't depend on Oracle/SQL packages.

While the library in Andrea's link is really cool (and I'd love to have a play with it) I'm not sure if it's necessary or particularly useful for something like this. We've found that putting in these kinds of architectural boundaries are much easier at a project-by-project level instead of a class-by-class level: it means the `public`/`internal` distinction does something much more useful, and it's much easier to check that project references are sensible than code references. AFAIK the SCA codebase already has quite a few tests that check certain project references are correct (mostly as a workaround for some weirdnesses when old/new csprojs reference each other). It doesn't feel like it would be too hard to use that code to build up a tree of project references in the solution and assert eg 1) it's actually a DAG 2) any db-specific (oracle or mssql) subtree is entirely db-specific, etc, without requiring an extra library.

While writing this I realised we do have a bunch of project-specific conventions that go along with the architecture (something like "each project must keep implementation details internal and expose only interfaces + an autofac module which provides the implementation") and the library looks like it might be really useful for implementing those sorts of checks.

(Also the above concept of "small SRP projects exposing an autofac module" is something I think we independently discovered in both SCA and Figleaf, or maybe carried over from one to the other, but I'm not sure if we've ever written it down anywhere - it's probably worth sharing more widely since it seems to work pretty well :)

**Comment by adrianbanks** [comment]
You can do this in Visual Studio using architecture dependency validation diagrams.

You draw some boxes for each component of your system, then drag the relevant projects into them. You can them set dependencies between the components. MsBuild understands the diagram format and can run a validation against it based on the the current project dependency graph, allowing you to fail a build when the validation fails.

**Comment by fffej** [comment]
@angellaa What's the sentiment here? Do you want to commit to explore it or given other comments maybe consider alternatives?

**Comment by fffej** [comment]
@angellaa I'm going to close this issue as I don't see any team commitment to explore it and as @adrianbanks and @nyctef have pointed out it looks like our current stack can do this without needing to introduce something more.

**Comment by angellaa** [comment]
Agree
