### ISSUE TITLE
Static/Dynamic code analysis tools

### ISSUE THREAD

**Issue by fredjeronimo** [red-gate/Tech-Radar#30]
In Prompt:

* [Sonarqube](https://www.sonarqube.org/) - Explore

I've used quite a few other tools in the past such as [Pc-Lint](https://www.gimpel.com/html/pcl.htm), [NDepend](https://www.ndepend.com/), FxCop/[StyleCop](https://github.com/StyleCop) and [Coverity](https://scan.coverity.com/). The latter is by far the most powerful one but it's quite expensive...

**Comment by smobs** [comment]
We use sonarqube on masketeers.  Feels like RG has adopted this

**Comment by nyctef** [comment]
+1 for not sure exactly how much value sonarqube provides - we have it on our PRs and it seems to occasionally pop up with some useful suggestions (and seems to be more intelligent / better at finding actual bugs than R# or compiler warnings) but we still spend a nonzero amount of time managing false positives and stuff we just don't care about.

**Comment by ChrisLambrou** [comment]
We use code inspections in R# and TeamCity in The Spiders. It's kind of annoying at times, but it's nonetheless keeping us honest for a good handful of basic code quality issues.

**Comment by garethbragg** [comment]
Considering how widely it's used, I do think Sonarqube should be in _Adopt_.

Quite happy for any alternatives to be in _Explore_.

**Comment by nyctef** [comment]
> Regarding the flakiness, look here: https://buildserver.red-gate.com/viewType.html?buildTypeId=CustomerDelight_SqlEstateManager_Web_2SonarqubeAnalysis

This appears to be the powershell + stderr + `rg-buildphy02` problem that's been popping up recently: (eg [\[1\]](https://redgate.slack.com/archives/C099Y4DH9/p1541159614017700) and [\[2\]](https://redgate.slack.com/archives/C099Y4DH9/p1542722472086200)) - it's really annoying but possible to work around so that the build doesn't fail because of random warnings.

> I'm a bit surprised this got promoted to Adopt to quickly given its luke-warm reception in this thread, and plenty of evidence that maintaining it is an annoyance and a distraction.

Well, it got promoted to Adopt since it's currently widely adopted, and we're currently just trying to model the existing state of the world here. We can definitely look into exploring alternatives as well (I know several teams use R# inspections for a similar thing and I think people have looked into StyleCop/FxCop/etc).

Personally I think the sonarqube inspections are slightly better / more useful than other tools I've used, but the build issues are annoying. Maybe it's just a case of picking one tool and sticking with it?

**Comment by ChrisLambrou** [comment]
If SonarQube requires a special workaround that no other tool seems to require, then maybe we should codify that workaround into a RedGate.Build cmdlet? e.g. invoke SonarQube analysis with `-ErrorAction Continue`, but separately capture any stderr output and subsequently raise an error directly in PowerShell if necessary? Would something like that sole the stability problems, or are they more wide reaching?

**Comment by ChrisLambrou** [comment]
Plus, adding support for SonarQube in RedGate.Build would mean I can get rid of stuff like [this](https://github.com/red-gate/SQLEstateManager-vNext/blob/master/.build/tasks/SonarQube.tasks.ps1) that I just don't want to have to maintain in our project's repo.

**Comment by nyctef** [comment]
> If SonarQube requires a special workaround that no other tool seems to require, then maybe we should codify that workaround into a RedGate.Build cmdlet?

Git actually [has the same problem](https://github.com/red-gate/data-masking/pull/1791#pullrequestreview-171105822) with powershell and stderr as well (although it turns out that git has a workaround built-in through [an environment variable you can set](https://git-scm.com/docs/git#git-codeGITREDIRECTSTDERRcode))

I agree we should probably pull something together in RedGate.Build for running sonarqube, though, for the reasons you said - it doesn't look like our various copies of `sonarqube.tasks.ps1` have diverged much.

**Comment by ChrisLambrou** [comment]
> I agree we should probably pull something together in RedGate.Build for running sonarqube, though, for the reasons you said - it doesn't look like our various copies of sonarqube.tasks.ps1 have diverged much.
👍 

They haven't diverged "much", which means they might have a little bit. That's grounds enough to pull it into RedGate.Build. I think that's my 10% time job for tomorrow! 😀
