### ISSUE TITLE
Configuration file format

### ISSUE THREAD

**Issue by smobs** [red-gate/Tech-Radar#32]
How do we store information in files?

Adopt - JSON
Endure - XML

**Comment by nyctef** [comment]
related: Registry - retire ?

**Comment by rmc47** [comment]
Sysadmin point of view note: Registry is a really handy way of pushing out individual settings across an organisation via group policy in a way that can't easily be done by mangling individual values within a config file.

**Comment by nyctef** [comment]
That's a good point - I guess for some options like the usage reporting opt-out or (hypothetical) autoupdate opt-out we'd probably want to keep in the registry for that reason

**Comment by ChrisLambrou** [comment]
Continued use of the registry is a blocker to .NET Standard adoption and cross-platform support. It's the only remaining reason the Usage Client still only supports Windows. Sigh...

**Comment by ChrisLambrou** [comment]
Well, I'm currently dealing with this at the DI level, with an OS/platform check:

https://github.com/red-gate/RedGate.Usage.Client/blob/non-windows-providers/RedGate.Usage.Client/UsageSessionFactory.cs#L54

That part's not difficult. The pain is that for a handful of interfaces, each has two implementations: one based on the registry for Windows, and one based on config files for Linux, Macs and everything else. It's just more costly to create and maintain, and doubles the chance of bugs.

**Comment by garethbragg** [comment]
Do we have a full house on this one?

Adopt: JSON
Endure: XML
Retire: Registry
Explore: Something-that-isn't-these-but-is-dotnetstd-and-is-good-for-sysadmins

**Comment by ChrisHurley** [comment]
Perhaps just worth noting if we're moving things out of the Registry that we might want some guidelines about where we do store configuration, or it'll be strewn all over and we might have issues with permissions (and e.g. what should be in Roaming vs Local)?

**Comment by rmc47** [comment]
If it's not registry, then there's nothing really consistently ubiquitous. Taking a leaf from the Linux world, the `conf.d` pattern of having a directory of included config files that get merged together is quite nice in that it allows you to create independent files with fixed content, rather than having your config management tool understand the configuration format.

For example, it's easy for me to drop a file with fixed contents into a place. It's harder for me to set one value in an existing JSON document that also contains other values that will get changed by other mechanisms. 

So if I want to force some CfU or Licensing setting across my organisation, having a `00-override-licensing.conf` file I can just drop on everyone's filesystem is easier than setting one attribute within a much larger JSON (or XML, or YAML, or whatever) file.

**Comment by fffej** [comment]
@smobs I've tried to sum up the configuration file format changes in the related PR - could you take a look and see if we can close this one out?
