### ISSUE TITLE
Blazor: Raise To Trial

### ISSUE THREAD

**Issue by madninjaskillz** [red-gate/Tech-Radar#361]
## What change would you like to make to the tech radar?
As Blazor is now released I flag that we should seriously consider upgrading its position to trial.

## Why do you believe this is valuable to Redgate?
Our current preferred UI technology, React, has a number of concerns that mean should the decision be revisited today, it may go in a different direction. Blazor, being a C# tech reduces the number domains that teams need to have. It allows more code sharing (or even often eliminating the need to share code at all) and generally feels a better fit for Redgate.

While at this point, embracing Blazor fully is probably a bad idea (a lot of investment has been made into React and HCPT), for any new products (such as Flyway Hub) I think it would make a very sensible option to gauge potential (and if the team on the new product are not au fait with React, possibly increase speed)

## Where should this be on the tech radar?
Assess

### If this should be in the _Explore_ ring, who is committed to exploring it?

**Comment by angellaa** [comment]
I guess the biggest barrier to Blazor adoption or even exploration is the lack of availability of components of the Honeycomb community. We know all our software UI should embrace the honeycomb design system. So is there any appetite to create a honeycomb-blazor spin off community as an attempt to explore this further? Is this a requirement for a successful exploration of Blazor? In the past we create #honeycomb-wpf so doing a honeycomb-Blazorf wouldn't be that different. As Blaroz is now more mature and released as GA (both Blazor server-side and web-assembly), I think the time has come to give it a proper go. The advantage of using C# client-side is obviously huge for .NET developers. Any other opinions?

**Comment by angellaa** [comment]
Maybe we could move your http://tldr.ezmuze.co.uk experiment to http://tldr.redgate.com and use that as a gym for playing with Blazor and honeycomb-blazor?

**Comment by fffej** [comment]
If Blazor was a success for us, what would that mean?

**Comment by matburton** [comment]
> If Blazor was a success for us, what would that mean?

Could you elaborate the question @fffej ?

Are you asking what criteria we'd use to judge whether any experiment was a success in this case?
Or are you asking what you happen (if anything) if any Blazor experiment was a success?

**Comment by fffej** [comment]
Both 😄 

React was successful enough that we've ported nearly all web-based products over to use it. Would we expect to do the same for Blazor?

There's value in homogeneity (training, portability, economies of scale) and we've got to be super clear that any new tech (*) will achieve more than what we've got.

(*) Tech that's hard to replace. Obviously the burden of proof for your average nuget package is tiny but something like a programming language or ingrained tech has a much higher burden.

**Comment by matburton** [comment]
> React was successful enough that we've ported nearly all web-based products over to use it. Would we expect to do the same for Blazor?

I my mind Blazor could be a better fit in a few instances:
1. Cases where the same logic or concepts are needed in the front-end and back-end (e.g. classic example is validation, but often the domain is shared and things like (de)serialisation and constants might be shared)
2. Cases where theam team is very familar with .NET and Razor and less familiar with JavaScript and its eco-system.
3. Cases where we want better end-to-end testing. e.g. a Blazor front-end that uses a client-library for an API where that client-library is tested against the API with automated tests.

> There's value in homogeneity (training, portability, economies of scale) and we've got to be super clear that any new tech (*) will achieve more than what we've got.

Blazor is appealing because it further limits non-domain cognative load since it's .NET and our back-ends will likley always be predominanly .NET. However if all Redgate staff are expected to be React/JS/TS (and the ecosystem) experts soon this does mean that (2) above is probably not as applicable now as it was a few years ago.

> Obviously the burden of proof for your average nuget package is tiny but something like a programming language or ingrained tech has a much higher burden.

Since Blazor builds upon .NET and Razor the burden is reduced compared to similar shifts (e.g. to React).

**Note**: I'm actually on the fence with Blazor. It has potential but hasn't had the uptake it maybe needs? It risks becoming the next Silverlight. SSR Blazor has been more the focus for Microsoft as of late, but AFAIK we haven't really made any SSR apps in React. Client-side Blazor is not very otimised and I'm not sure that's going to change any time soon. The bundle sizes might be too large for us to consider using it in our products?

**Comment by fffej** [comment]
After much discussion in the LSE meeting, I've taken the decision to move Blazor to "hold", explicitly calling out that we should **not** use this for new projects.

Why?

We're close to standardizing all of our products on a React tech stack, and opening up exploration of Blazor would halt this work. 

Blazor looks great and could potentially offer us some advantages, but we've no company level experience of it with real products, and therefore it's too much of an unknown to start deploying into production.
