### ISSUE TITLE
Release management

### ISSUE THREAD

**Issue by smobs** [red-gate/Tech-Radar#38]
* Adopt - Releasing via a single script
* Endure - Manual releases via the release app

**Comment by fffej** [comment]
Do we _really_ want to continue doing manual releases? (disclaimer: don't know how many teams currently do this!).

**Comment by nyctef** [comment]
As far as I know most teams now have release scripts, but Prompt and DMv6 are still missing them (we just haven't gotten around to writing that latter one since we release that pretty infrequently). I'd definitely be up for actively trying to retire any manual release processes that we have (including cleaning up some release scripts which are mostly-automatic but have some manual bits at the end)

(plus it'd be a good excuse to put more investment into dtw-docs >.>)

**Comment by garethbragg** [comment]
I'd be keen for manual releases to be in _Retire_.

I don't think that would force "Move DMv6 over to release scripts" to be a top priority. Leaving that alone seems a pragmatic choice, unless the team think otherwise. I see this as an outlier, which I don't think should have too strong an influence on the tech radar?

(Please do challenge me if you think we should "document the lowest denominator".)

I'd encourage SQL Prompt to use release scripts, though. I'm surprised to hear the product isn't already.

**Comment by samblackburn** [comment]
1. Adopt `basic-release.ps1` if possible, does what most products need in one line
2. The rest of RG.Release is there if your release process differs slightly
3. Arbitrary PowerShell if you're doing stuff no other product needs to do
4. Manual processes for whatever you can't automate

**Comment by ChrisLambrou** [comment]
Rob Chipperfield has always chimed in on this subject in the past, with good arguments about requiring releases to be traceable to specific individuals, possibly for legal reasons. It's definitely worth bringing this issue to his attention, which I can't do right now because the mobile GitHub app is properly pants!

**Comment by rmc47** [comment]
Sorry, that was long and waffly. TLDR: yes, current scripted releases tick all the boxes!

**Comment by fffej** [comment]
Anyone fancy bringing this to a head with a PR? 🙏
