### ISSUE TITLE
Scope of Explore Ring - commitment and accountability?

### ISSUE THREAD

**Issue by tugberkugurlu** [red-gate/Tech-Radar#43]
Currently, the scope of Explore ring is as below:

> This has potential and is worth experimenting with in 10% time or running a trial on your team.

One can infer from this that this can be a wishlist of what we want to look into. I can see a value of this. However, in scope of Tech-Radar, it might be more effective to us to constraint this ring to only hold items which teams are actively trying out.

So, I propose that we change the scope of this to emphasise:

 - commitment: Only an actively explored item which is associated to a quadrant should be in here. We should also make it clear what the expected outcome we are hoping from this exploration to put clarity on the success.  
 - accountability: I believe there should be accountability associated with exploring a an item under a quadrant. There should be a point that the team should make it visible to the rest of the product division what the results of the exploration was and what the recommendation is (e.g. take it to Adopt, make a case for more knowledge investment, stop exploring and endure/retire, etc.).

There are a few outcomes I expect us to achieve through this change:

 - Make it more clear what Explore ring means to us.
 - As a result of above, we should be able to make decisions faster on what should go into here.
 - Prevent making this ring to be our wishlist of the hot technologies/techniques/platforms/etc. w/o any real benefit to us.
 - As we have accountability associated to each item under here associated to a quadrant, it can make it more clear what the next steps could be. Obviously, it's another matter to make sure we regularly review.

**Comment by garethbragg** [comment]
My "worry" with this approach is that we don't show anything Redgate _wants_ to explore but hasn't started yet. Presenting this has some benefits:

* Encourages people to try out _relevant_ new stuff, rather than picking any arbitrary shiny-shiny
* Puts pressure on us to draw explorations to an end so we can move on to other ideas

Reading them back, these don't feel especially well aligned with our moratorium on new tech.

How about this?

_For now_, we adopt @tugberkugurlu's definition of _Explore_.  This allows us to build a rich picture of where we currently are, and what we're currently exploring/retiring/etc.

When we get the number of in-use techs down (i.e. when the moratorium can be lifted?), we review what we mean by _Explore_ to see if we want to allow "wishlist" items.

**Comment by ChrisHurley** [comment]
I do think that there needs to be some sort of process around things moving between rings - if something is in "explore" it needs to eventually move somewhere else (or fall off the radar entirely). It does feel that it needs regular review and some guidance - am I allowed to use things in "explore" in product code because I fancy giving them a try, or does this mean that they're being evaluated in some organised way and I should wait to see where that goes?

**Comment by fffej** [comment]
@tugberkugurlu There's a PR with some suggestions around this - what'd you think?

**Comment by tugberkugurlu** [comment]
closed by https://github.com/red-gate/Tech-Radar/pull/53
