### ISSUE TITLE
Testing framework (Powershell)

### ISSUE THREAD

**Issue by nyctef** [red-gate/Tech-Radar#62]
Pulling this out of https://github.com/red-gate/Tech-Radar/issues/27:

> Does Pester count as a testing framework for .NET? It's for PowerShell! 😁

Are there any alternatives to Pester we should be considering?

**Comment by fffej** [comment]
Paging @ChrisLambrou - is Pester something we're actively using already that you'd recommend for everyone? Or is it something we should explore as a way of testing Powershell?

**Comment by ChrisLambrou** [comment]
It's pretty much the de-facto testing framework for PowerShell. So much so that the Pester module comes pre-installed with PowerShell, though you typically need to update it. We use it in places where we're working in with PowerShell rather than directly with .NET code. I can think of [RedGate.Build](https://github.com/red-gate/RedGate.Build/tree/master/Tests) _(our best example)_ and the [DLMA VSTS plugin](https://github.com/red-gate/DLMAutomation/tree/master/AddOns/VSTSRelease/Tests), but there are probably others.

Actually, here's a [useful search link](https://github.com/search?l=PowerShell&q=org%3Ared-gate+%22Describe%22&type=Code) for a Pester test fixture in our own code. It seems we have a fair handful of repos already using it. Also, it has [good test results integration with TeamCity](https://buildserver.red-gate.com/viewLog.html?buildId=9618764&buildTypeId=BuildSystem_RedGateBuild&tab=testsInfo) too, and [good build output when running from one of our PowerShell build scripts](https://buildserver.red-gate.com/viewLog.html?buildId=9618764&buildTypeId=BuildSystem_RedGateBuild&tab=buildLog&_focus=159#_state=118,119).

Personally, I'd classify Pester as Adopt. Right now, if you want a testing framework for PowerShell, I don't know of any better alternatives, and we have evidence of it working well in multiple projects.

**Comment by fffej** [comment]
@ChrisLambrou Happy to go with that, want to make a PR?

**Comment by ChrisLambrou** [comment]
Okay, will do.

**Comment by ChrisLambrou** [comment]
And [done](https://github.com/red-gate/Tech-Radar/pull/67). Assigned to Jeff, but I guess anyone could review and merge this, right?
